image-boot: Remove device mapper, mount loopback devices directly
After removing the extent mapping approach for image booting,
we are left with a simpler code flow logic with some obvious calls
for simplification.

After we set up the loopback device, we were setting up a device-mapper
linear mapping against it. That had the function of handling non-standard
sector sizes when booting from DVD (which we no longer care about).
Then another linear mapping was placed on top when creating partitions.
Another useful function of the mapping was to give the final root
device a stable name (/dev/mapper/endless-image*), used by the
subsequent initramfs logic, and also by eos-installer when seeking
source image for installation.

Eliminating the device mapper bits for simplicity, we now set up
a symlink at /dev/disk/endless-image which points to the loop device
that we are booting from.

https://phabricator.endlessm.com/T35126

diff --git a/dracut/image-boot/eos-image-boot-setup b/dracut/image-boot/eos-image-boot-setup
--- a/dracut/image-boot/eos-image-boot-setup
+++ b/dracut/image-boot/eos-image-boot-setup
@@ -9,19 +9,16 @@ if [ $# -ge 1 ]; then
   # For testing
   if [ "$1" = "--readonly" ]; then
     shift
-    dm_roflag=--readonly
-    kpartx_roflag=-r
+    disk_ro=1
   fi
 
   host_device="$1"
   image_path="$2"
-  target_name="$3"
 else
   type getarg >/dev/null 2>&1 || . /lib/dracut-lib.sh
 
   image_device=$(getarg endless.image.device)
   image_path=$(getarg endless.image.path)
-  target_name=endless-image
 
   # When booting an ISO using HD emulation (e.g. booting an ISO file flashed
   # to USB), udev records that the ISO UUID applies to both the iso9660
@@ -41,13 +38,10 @@ else
   # If possible, create partition for persistent data storage
   eos-live-storage-setup "${host_device}"
 
-  blockdev --setro ${host_device}
-
-  if getargbool 0 endless.live_boot; then
-    dm_roflag=--readonly
-    kpartx_roflag=-r
-  fi
+  getargbool 0 endless.live_boot && disk_ro=1
 fi
+
+[ -n "${disk_ro}" ] && blockdev --setro ${host_device}
 
 fstype=$(lsblk --noheadings -o FSTYPE "${host_device}")
 if [ $? != 0 ]; then
@@ -62,17 +56,6 @@ case "$image_path" in
 *.squash)  squashfs=1 ;;
 *)         squashfs=  ;;
 esac
-
-linear_map() {
-  # Create a device-mapper linear device corresponding to the given loopback.
-  local device="${1:?}"
-  local size_bytes=$(lsblk --output SIZE --nodeps --bytes --noheadings ${device})
-  if ! echo "0 $((size_bytes / 512 )) linear ${device} 0" \
-    | dmsetup create $target_name $dm_roflag; then
-    echo "Failed to create linear device for ${device}" >&2
-    exit 1
-  fi
-}
 
 # Identify the EOS image extents on the host device, and create a dm-linear
 # block device that maps exactly to that. If the image is a squashfs, then
@@ -93,7 +76,7 @@ if ! mount -t $fstype ${host_device} /outer_image; then
   exit 1
 fi
 
-# Create a loopback device backing the squashfs
+# Create a loopback device backing the image
 image_device=$(losetup -f)
 losetup ${image_device} /outer_image/${image_path}
 if [ $? != 0 ]; then
@@ -105,24 +88,42 @@ fi
 # uncompressed image within it
 if [ -n "$squashfs" ]; then
   # Mount the squashfs
-  squash_device="$image_device"
   mkdir /squash
-  if ! mount ${squash_device} /squash; then
-    echo "Failed to mount ${squash_device}"
+  if ! mount ${image_device} /squash; then
+    echo "Failed to mount ${image_device}"
     exit 1
   fi
 
   # Create a loopback device backing the endless image
-  host_device=$(losetup -f)
-  losetup ${host_device} /squash/endless.img
-  linear_map "$host_device"
-else
-  linear_map "$image_device"
+  image_device=$(losetup -f)
+  losetup ${image_device} /squash/endless.img
 fi
 
-if ! kpartx $kpartx_roflag -a -v /dev/mapper/$target_name; then
+if ! partx -a -v "${image_device}"; then
   echo "image-boot: failed to probe partitions"
   exit 1
 fi
+
+# Setup a stable /dev/disk/endless-image symlink for our image device and
+# partitions.
+#
+# This is used by eos-installer, which doesn't have the knowledge how
+# to find the image inside a squashfs, so it uses this path. This also
+# requires the device node to have appropriate permissions.
+# This path is also used by the rest of the initramfs which is hardcoded
+# to find the rootfs at /dev/disk/endless-image3.
+image_device_name="${image_device##*/}"
+mkdir -p /run/udev/rules.d
+cat <<EOF > /run/udev/rules.d/70-endless-image.rules
+SUBSYSTEM=="block", KERNEL=="${image_device_name}", MODE="0664", SYMLINK+="disk/endless-image"
+SUBSYSTEM=="block", KERNEL=="${image_device_name}p?", MODE="0664", SYMLINK+="disk/endless-image%n"
+EOF
+
+udevadm control --reload-rules
+
+# Ideally these rules could be placed before the disk devices appear and they
+# would then kick in automatically, but in practice, since there are some
+# devices like loop0 which always exist, it is necessary to explicitly trigger.
+udevadm trigger "${image_device}"
 
 exit 0
