image-boot: split out image mapping logic
This makes it easier to test interactively, and easier to refactor
eos-image-boot-setup to support SquashFS on non-ISO9660 partitions.

diff --git a/dracut/image-boot/eos-image-boot-setup b/dracut/image-boot/eos-image-boot-setup
--- a/dracut/image-boot/eos-image-boot-setup
+++ b/dracut/image-boot/eos-image-boot-setup
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Copyright (C) 2016 Endless Mobile, Inc.
+# Copyright (C) 2016-2017 Endless Mobile, Inc.
 # Licensed under the GPLv2
 #
 # Support booting from an image file hosted on a filesystem.
@@ -29,11 +29,11 @@ fi
 # block device that maps exactly to that.
 
 case "${fstype}" in
-exfat)
-  extents=$(dumpexfat -f "${image_path}" "${host_device}")
-  ;;
-ntfs)
-  extents=$(ntfsextents "${host_device}" "${image_path}")
+exfat | ntfs)
+  if ! eos-map-image-file "${host_device}" "${image_path}" endless-image; then
+    echo "Failed to map ${image_path} on ${host_device}" >&2
+    exit 1
+  fi
   ;;
 iso9660)
   # Mount the ISO image
@@ -61,41 +61,16 @@ iso9660)
 
   # Create a device-mapper linear device corresponding to the loopback
   size_bytes=$(lsblk --output SIZE --nodeps --bytes --noheadings ${host_device})
-  extents="0 ${size_bytes}"
+  if ! echo "0 $((size_bytes / 512 )) linear ${host_device} 0" \
+    | dmsetup create endless-image $dm_roflag; then
+    echo "Failed to create linear device for ${host_device}" >&2
+    exit 1
+  fi
   ;;
 *)
   echo "image-boot: unsupported filesystem ${fstype}"
   exit 1
 esac
-
-if [ $? != 0 ]; then
-  echo "image-boot: failed to lookup image on device"
-  exit 1
-fi
-
-offset=0
-echo "$extents" | while read extent_offset extent_size; do
-  [ -z "${extent_offset}" -o -z "${extent_size}" ] && continue
-  # Convert bytes to sectors, rounding up
-  if [ $(( extent_size % 512 )) != 0 ]; then
-    echo "image-boot: extent size $extent_size not sector-aligned" >&2
-    exit 1
-  fi
-  extent_size=$(( extent_size / 512 ))
-  extent_offset=$(( extent_offset / 512 ))
-  echo "${offset} ${extent_size} linear ${host_device} $extent_offset"
-  offset=$((offset + extent_size))
-done > /tmp/dmtable
-
-if [ $? != 0 ]; then
-  exit 1
-fi
-
-dmsetup create endless-image $dm_roflag < /tmp/dmtable
-if [ $? != 0 ]; then
-  echo "image-boot: failed to set up linear mapping"
-  exit 1
-fi
 
 if ! kpartx $kpartx_roflag -a -v /dev/mapper/endless-image; then
   echo "image-boot: failed to probe partitions"
