zram: Use consistent indentation

diff --git a/eos-enable-zram b/eos-enable-zram
--- a/eos-enable-zram
+++ b/eos-enable-zram
@@ -3,8 +3,8 @@
 # Licensed under the GPLv2
 
 if [ $# -lt 1 -o "$1" -lt 0 -o "$1" -gt 1 ]; then
-	echo "Error: 0 or 1 must be specified" >&2
-	exit 1
+    echo "Error: 0 or 1 must be specified" >&2
+    exit 1
 fi
 
 if [ "$1" -eq 0 ]; then
